### PR TITLE
Import what we need from the typing module

### LINKED ISSUE #6: Do we need to import Tuple/List etc from typing?

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Closes #6.

### CODE REVIEW

**Comment by ghost** [comment]
Looks good to me - and after testing does indeed function correctly.

Would you be able to modify the test cases to include this import please?

(I'm aware how painfully brittle they are, I'm quite tempted to remove/disable them at this point)

**Comment by GrahamCampbell** [comment]
@wjh I think this is good to merge now?

**Comment by GrahamCampbell** [comment]
@wjh I think this is good to merge now?

**Comment by ghost** [comment]
This is great, thanks!

**Pull request merged**
