### PR TITLE
Fixed generation of default methods

### PR DESCRIPTION
**Pull request by GrahamCampbell**
I'll update the tests after my other PR is done.

### CODE REVIEW

**Comment by ghost** [comment]
This is great, thanks! Just let me know when you're done with all the changes and I'll get these merged for you.

**Comment by GrahamCampbell** [comment]
Ok, I'll update the tests now, and we can do this one first.

**Comment by GrahamCampbell** [comment]
This is good to merge now I think. I'll update #7 right after.

**Comment by ghost** [comment]
Fantastic, thank you!

**Pull request merged**
